import turtle
import numpy as np


def print_one(x):
    turtle.right(90)
    turtle.forward(x)
    turtle.left(135)
    turtle.pendown()
    turtle.forward(np.sqrt(2) * x)
    turtle.right(135)
    turtle.forward(2 * x)
    turtle.penup()
    turtle.left(90)
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(2 * x)
    turtle.right(90)


def print_two(x):
    turtle.pendown()
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.penup()
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(2 * x)
    turtle.right(90)


def print_three(x):
    turtle.pendown()
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(180)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.penup()
    turtle.right(180)
    turtle.forward(2 * x)
    turtle.left(90)
    turtle.forward(2 * x)
    turtle.right(90)


def print_four(x):
    turtle.pendown()
    turtle.right(90)
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.left(180)
    turtle.forward(2 * x)
    turtle.left(90)
    turtle.penup()
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(2 * x)
    turtle.right(90)


def print_five(x):
    turtle.forward(x)
    turtle.right(180)
    turtle.pendown()
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.penup()
    turtle.right(180)
    turtle.forward(2 * x)
    turtle.left(90)
    turtle.forward(2 * x)
    turtle.right(90)


def print_six(x):
    turtle.forward(x)
    turtle.right(180)
    turtle.pendown()
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.left(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(x)
    turtle.penup()
    turtle.right(90)
    turtle.forward(2 * x)
    turtle.left(90)
    turtle.forward(x)
    turtle.right(90)


def print_seven(x):
    turtle.forward(x)
    turtle.right(135)


turtle.shape('turtle')
turtle.speed(5)
turtle.penup()
print_four(50)
print_five(50)
print_six(50)
print_two(50)
